---

- hosts: all
  vars:
    ansible_python_interpreter: auto
  become: true
  tasks:

  - name: Install apache and php packages and Update cache
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
