---

- hosts: all
  vars:
    ansible_python_interpreter: auto
  become: true
  tasks:

  - name: Remove apache and php for Ubuntu servers
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Remove httpd and php for Red Hat servers
    dnf:
      name: 
        - httpd
        - php
      state: absent
      update_cache: yes
    when: ansible_distribution == "Red Hat"
