---

- hosts: all
  vars:
    ansible_python_interpreter: auto
  become: true
  tasks:

  - name: Remove apache and php packages
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
      update_cache: yes
