---

- hosts: all
  vars:
    ansible_python_interpreter: auto
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove php support for apache
    apt:
     name: libapache2-mod-php
     state: absent
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: remove httpd package
    dnf:
      name: httpd
      state: absent
    when: ansible_distribution == "RedHat"

  - name: remove php support for apache
    dnf:
     name: php
     state: absent
    when: ansible_distribution == "RedHat"
