---

- hosts: all
  become: true
  pre_tasks:

  - name: Install Updates (Arch)
    pacman:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Archlinux"
    tags: always

  - name: Install Updates (Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"
    tags: always

  - name: Install Updates (Kali)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Kali GNU/Linux"
    tags: always

  - name: Install Updates (Mint)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Linux Mint"
    tags: always

  - name: Install Updates (Rocky)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"
    tags: always

  - name: Install Updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    tags: always

- hosts: workstations
  become: true
  tasks:
  - name: Install unzip
    package:
      name: unzip

  - name: Install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.4/terraform_1.3.4_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      owner: root
      group: root
      mode: 0755

- hosts: web_servers
  become: true
  tasks:

  - name: Install Apache and PHP for Red Hat Servers
    tags: apache,redhat,httpd
    dnf:
      name:
        - httpd
        - php
        - php-pdo
        - php-gd
        - php-mbstring
      state: latest
    when: ansible_distribution == "RedHat"

  - name: Install Apache and PHP for Rocky Servers
    tags: apache,redhat,httpd
    dnf:
      name:
        - httpd
        - php
        - php-pdo
        - php-gd
        - php-mbstring
      state: latest
    when: ansible_distribution == "Rocky"

  - name: Install Apache and PHP for Ubuntu Servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install Apache and PHP for Debian Servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"

  - name: Copy default html file for site
    tags: apache,apache2,debian
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB package (Arch Linux)
    tags: arch64,db,mariadb
    pacman:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "Archlinux"

  - name: Install MariaDB package (Debian)
    tags: db,mariadb,ubuntu
    apt:
      name: 
        - mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

  - name: Install MariaDB package (Kali GNU/Linux)
    tags: arch64,db,mariadb
    apt:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "Kali GNU/Linux"

  - name: Install MariaDB package (Rocky Linux)
    tags: arch64,db,mariadb
    dnf:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "Rocky"

  - name: Install MariaDB package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: Install Samba package on File Servers
    tags: samba
    package:
      name: samba
      state: latest
