---

- hosts: all
  vars:
    ansible_python_interpreter: auto
  become: true
  pre_tasks:

  - name: Install Updates (Red Hat)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"
    tags: always

  - name: Install Updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    tags: always
      
- hosts: web_servers
  vars:
    ansible_python_interpreter: auto
  become: true
  tasks: 

  - name: Install Apache and PHP for Red Hat Servers
    tags: apache,redhat, httpd
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

  - name: Install Apache and PHP for Ubuntu Servers
    tags: apache,apache2,ubuntu
    dnf:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  vars: 
    ansible_python_interpreter: auto
  become: true
  tasks:

  - name: Install MariaDB package (Red Hat)
    tags: redhat,db,mariadb
    dnf:
      name: 
        - mariadb
      state: latest
    when: ansible_distribution == "RedHat"

  - name: Install MariaDB package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: 
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  vars: 
    ansible_python_interpreter: auto
  become: true
  tasks:

  - name: Install Samba package on File Servers
    tags: samba
    package:
      name: samba
      state: latest
