---

- hosts: all
  become: true
  pre_tasks:

  - name: Install Updates (Red Hat)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"
    tags: always

  - name: Install Updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    tags: always
- hosts: workstations
  become: true
  tasks:
  - name: Install unzip
    package:
      name: unzip

  - name: Install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.4/terraform_1.3.4_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      owner: root
      group: root
      mode: 0755
      
- hosts: web_servers
  become: true
  tasks: 

  - name: Install Apache and PHP for Red Hat Servers
    tags: apache,redhat, httpd
    dnf:
      name: 
        - httpd
        - php
        - php-pdo 
        - php-gd
        - php-mbstring
      state: latest
    when: ansible_distribution == "RedHat"

  - name: Install Apache and PHP for Ubuntu Servers
    tags: apache,apache2,ubuntu
    dnf:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB package (Red Hat)
    tags: redhat,db,mariadb
    dnf:
      name: 
        - mariadb
      state: latest
    when: ansible_distribution == "RedHat"

  - name: Install MariaDB package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: 
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: Install Samba package on File Servers
    tags: samba
    package:
      name: samba
      state: latest
