---

- hosts: all
  become: true
  pre_tasks:

  - name: Update Repo Cache (Arch)
    pacman:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Archlinux"
    tags: always

  - name: Update Repo Cache (debian)
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Debian"
    tags: always

  - name: Update Repo Cache (Kali)
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Kali GNU/Linux"
    tags: always

  - name: Update Repo Cache (Mint)
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Linux Mint"
    tags: always

  - name: Update Repo Cache (Rhel8/9)
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "RedHat"
    tags: always

  - name: Update Repo Cache (Rocky)
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Rocky"
    tags: always

  - name: Update Repo Cache (Ubuntu)
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
    tags: always

- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers
