- name: Install Apache and PHP for Red Hat Servers
  tags: apache,redhat,httpd
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: Start and Enable apache service
  tags: apache,httpd
  service: 
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Change e-mail address for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regex: '^ServerAdmin'
    line: ServerAdmin nafur-tech@basedeep.net
  when: ansible_distribution == "Rocky"
  notify: restart_apache

- name: Copy default html file for site
  tags: apache,apache2,debian
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
